In [121]:
import numpy as np
import pandas as pd
import bokeh
import pickle

In [122]:
drivers=pd.read_pickle('final_drivers.pickle')
accidents=pd.read_pickle('final_accidents2.pickle')
speed=np.array(drivers['SPEEDREL'])

In [119]:
dri10=pd.DataFrame(drivers[drivers['YEAR']==2010])
acc10=pd.DataFrame(accidents[accidents['YEAR']==2010])
s=pd.DataFrame(dri10.groupby('ST_CASE').max()['SPEEDREL'])
#!!the drivers and accidents data do not match

         SPEEDREL
ST_CASE
10001           0
10002           0
10003           1
10004           0
10005           0
10006           0
10007           0
10008           0
10009           1
10010           0
10011           1
10012           1
10013           0
10014           0
10015           0
10016           0
10017           1
10018           0
10019           0
10020           1
10021           1
10022           0
10023           0
10024           0
10025           0
10026           0
10027           1
10028           1
10029           1
10030           1
...           ...
560110          1
560111          1
560112          0
560113          9
560114          9
560115          1
560116          0
560117          1
560118          1
560119          1
560120          0
560121          0
560122          0
560123          0
560124          0
560125          0
560126          1
560127          0
560128          1
560129          0
560130          1
560131          0
560132          1
560133          0
560134          1
560135          0
560136          1
560137          0
560138          0
560139          0

[30218 rows x 1 columns]

In [126]:
import pyproj
from_proj = Proj(init="epsg:4326")
to_proj = Proj(init="epsg:3857")
def convert(longitudes, latitudes):
    """Converts latlon coordinates to meters.
    Inputs:
        longitudes (array-like) : array of longitudes
        latitudes (array-like) : array of latitudes
    Example:
        x,y = convert(accidents.LONGITUD, accidents.LATITUDE)
"""
    x_vals = []
    y_vals = []
    for lon, lat in zip(longitudes, latitudes):
        x, y = transform(from_proj, to_proj, lon, lat)
        x_vals.append(x)
        ï¿¼y_vals.append(y)
    return x_vals, y_vals

NameError: name 'Proj' is not defined